# Generated by Django 3.0.14 on 2022-11-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('discount_price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('desciption', models.TextField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
